upstream blog {
    server blog:5000;
}

upstream shop {
    server shop:5001;
}

server {
    listen 80;
    server_name blog.localhost;

    location / {
        proxy_pass http://blog/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

server {
    listen 80;
    server_name shop.localhost;

    location / {
        proxy_pass http://shop/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

server {
    listen 80;
    server_name localhost;

    location / {
        return 301 http://blog.localhost:8080/;
    }
}